# Generated by Django 4.2.9 on 2024-01-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
